sudo: required
dist: trusty

notifications:
  email: false

before_install:
  # for g++4.8 and C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # for solc
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo add-apt-repository -y ppa:ethereum/ethereum-dev

  # solc setup
  - sudo apt-get update -y -qq
  - sudo apt-get install -yqq solc

script: cd tests && ./test.py --compile-test
